<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Persistence\Repositories\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\NexaAI.Application\NexaAI.Application.csproj" />
      <ProjectReference Include="..\NexaAI.Domain\NexaAI.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.30" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.30" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.30">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.7.3" />
    </ItemGroup>

</Project>
